name: Create
on:
  push:
    branches: [ main ]
  
jobs:
  build:
    name: Build Branch
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: upload build
      uses: pmuraus/spotlight-upload-action@main
      with: 
        buildName: "Action build"
        buildVersion: "1.1.1"
        files: "./README.md,./tools/package.json"
        apiKey: ${{secrets.SPOTLIGHT_KEY}}